import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import TasksContextProvider from "@/contexts/tasks-context";
import TaskActionDialogContextProvider from "@/contexts/taskaction-dialog-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <TasksContextProvider>
              <TaskActionDialogContextProvider>
                  {children}
              </TaskActionDialogContextProvider>
          </TasksContextProvider>
          </body>
    </html>
  );
}
